### PR TITLE
feat: Move all Binder config files to binder directory

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Add binder directory to make it clear to Binder where to find files.
* Move requirements.txt to binder/ and then symlink back to top level for user ease of use.
   - c.f. https://github.com/gradhep/differentiable-analysis-examples/pull/1 for an example
* Add binder/runtime.txt to specify a Python runtime of Python 3.10.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your pull request.

\- HSF Training
</details>

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@klieret this is ready for review. This can provide Binder stability by specifying more of the runtime.

**Comment by amangoel185** [comment]
@matthewfeickert, would it be better to update the Binder (and SWAN) link too? Currently points to @plttraining (https://mybinder.org/v2/gh/plttraining/hsf_matplotlib_notebooks/main) since it was ported to @hsf-training from there.

They work well already though!

**Comment by matthewfeickert** [comment]
@amangoel185 Done now with

```
git grep --name-only "plttraining" | xargs sed -i "s/plttraining/hsf-training/g"
```

so should have gotten everything.

**Comment by amangoel185** [comment]
Looks great, thank you! :)

**Pull request merged**
