### PR TITLE
Improve plot quality for jupyter-notebooks

### PR DESCRIPTION
**Pull request by amanmdesai**
I have added 
plt.rcParams['figure.dpi'] = 300
to the jupyter-notebooks which will improve the quality of images.

### CODE REVIEW

**Comment by klieret** [comment]
Hi @amanmdesai : Thank you for this. I'm a bit unsure about this, because it seems like a bit of a matter of taste? (I usually stick with the default 100dpi)

Also in general unsure about how we want to continue the development of this repository, see https://github.com/hsf-training/hsf-training-matplotlib/issues/66  -- your change might currently be easily overwritten the next time someone manually copies everything here)

**Comment by amanmdesai** [comment]
Hi, 
When I run the code, I see the plots a bit blurred so I thought to improve the picture quality. 

Since there is a discussion in https://github.com/hsf-training/hsf-training-matplotlib/issues/66, we can discuss about the image quality later at some later stage.  

Thanks.

**Comment by klieret** [comment]
This should be the same images as included in the webpage, right?

**Comment by amanmdesai** [comment]
Yes, the same images. The quality of images on webpage will need to be improved as well.

**Comment by klieret** [comment]
Is there any specific one that you find particularly problematic? Because for me this is still an acceptable compromise... (and increasing the dpi 3-fold will mean an almost 10x increase in file sizes...)

**Comment by amanmdesai** [comment]
Ah, 10 fold is quite a increase in the file size. In that case, its no use to improve the quality.

**Comment by klieret** [comment]
(That's my naive calculation because 3*3 = 9 ~ 10 for the 3-fold increase in dpi)

**Comment by amanmdesai** [comment]
Right. Shall I close this pull request?

**Comment by klieret** [comment]
Yeah, I'm in favor of it (though I'm sorry because you spent time on it)

**Comment by amanmdesai** [comment]
Oh no problem. I should have checked the file size.

Thanks.

**Pull request closed without merging**
